version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    expose:
      - 8000
    environment:
      - DJANGO_SETTINGS_MODULE=rencraft_backend.settings # Adjust your Django production settings
    command: gunicorn rencraft_backend.wsgi:application --bind 0.0.0.0:8000
    networks:
      - nginx-proxy

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./rencraft_backend/static:/app/static
    depends_on:
      - web
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    driver: bridge
